services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./db:/data/db
      # - ./configdb:/data/configdb
    networks:
      - tfd-hamja-net
  app:
    image: node:20-alpine
    depends_on:
      - db
    ports:
      - "0.0.0.0:3000:3000"
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"
    environment:
      - mongodb=mongodb://root:root@db:27017/?retryWrites=true&w=majority
      - host=http://0.0.0.0:3000
      - collection_prefix=tfd
      - db_name=MakkaKim-M0
      - NEXTAUTH_URL=http://localhost:3000
    networks:
      - tfd-hamja-net
volumes:
  node_modules:
networks:
  tfd-hamja-net: